---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: False

  vars_files:
    - vars/credentials.yml
    - vars/droplets.yml

  tasks:
    - shell: ./dohosts --all
      register: result

    - set_fact:
        droplets: "{{ (result.stdout|from_json).droplets }}"
        domains: "{{ (result.stdout|from_json).domains }}"

    - include: tasks/destroy_droplet.yml droplets={{droplets}}
    - include: tasks/destroy_domain.yml domains={{domains}}
