---
- hosts: builder
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/credentials.yml

  tasks:

    - name: Update APT cache
      apt: update_cache=yes

    - name: Install Raring kernel images
      apt: name=linux-image-generic-lts-raring state=present

    - name: Install Raring kernel headers
      apt: name=linux-headers-generic-lts-raring state=present

    - name: Restart server
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for server to come back
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started
      sudo: false

    - name: Add Docker APT key 
      apt_key: url=https://get.docker.io/gpg state=present

    - name: Add Docker APT repository
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present

    - name: Update APT cache
      apt: update_cache=yes

    - name: Install Docker
      apt: name=lxc-docker state=present
