---
- hosts: localhost
  connection: local
  serial: 1
  gather_facts: False

  vars_files:
    - vars/credentials.yml
    - vars/provision_hosts.yml

  tasks:
    - include: tasks/create_droplet.yml droplets={{droplets_to_provision}}
