---
- name: Ensure Droplet does not exist
  digital_ocean: >
    state=absent
    command=droplet
    id={{ item.id }}
    client_id={{ do_client_id }}
    api_key={{ do_api_key }}
  with_items: droplets

- name: Ensure Droplet host key removed from known_hosts
  shell: ssh-keygen -f "/home/jason/.ssh/known_hosts" -R {{ item.ip_address }}
  with_items: droplets
